### ISSUE TITLE
Corrupt YAML file after edit

### ISSUE THREAD

**Issue by dotkim** [hakash/jotr#10]
related issue: #8 

## Envirnoment
OS: Windows 10 build 1809
Shell: Powershell 5.1, CMD

## Error message
```powershell
PS C:\Users\[username]\Documents\certs> jotr --list
[loadJots] There was a problem interpreting the file. It seems to be corrupted in some way. Run "jotr --list --debug" to display the error message.

PS C:\Users\[username]\Documents\certs> jotr --list --debug
[loadJots] loading jots
[loadJots] There was a problem interpreting the file. It seems to be corrupted in some way. Run "jotr --list --debug" to display the error message.
[loadJots] Error message: { YAMLException: the stream contains non-printable characters at line 31, column 89:
     ... .citrix.instantpassthru
                                         ^
    at generateError (C:\Users\[username]\AppData\Roaming\npm\node_modules\jotr\node_modules\js-yaml\lib\js-yaml\loader.js:165:10)
    at throwError (C:\Users\[username]\AppData\Roaming\npm\node_modules\jotr\node_modules\js-yaml\lib\js-yaml\loader.js:171:9)
    at captureSegment (C:\Users\[username]\AppData\Roaming\npm\node_modules\jotr\node_modules\js-yaml\lib\js-yaml\loader.js:259:7)
    at readPlainScalar (C:\Users\[username]\AppData\Roaming\npm\node_modules\jotr\node_modules\js-yaml\lib\js-yaml\loader.js:506:3)
    at composeNode (C:\Users\[username]\AppData\Roaming\npm\node_modules\jotr\node_modules\js-yaml\lib\js-yaml\loader.js:1348:20)
    at readBlockMapping (C:\Users\[username]\AppData\Roaming\npm\node_modules\jotr\node_modules\js-yaml\lib\js-yaml\loader.js:1009:16)
    at composeNode (C:\Users\[username]\AppData\Roaming\npm\node_modules\jotr\node_modules\js-yaml\lib\js-yaml\loader.js:1332:12)
    at readBlockSequence (C:\Users\[username]\AppData\Roaming\npm\node_modules\jotr\node_modules\js-yaml\lib\js-yaml\loader.js:928:5)
    at composeNode (C:\Users\[username]\AppData\Roaming\npm\node_modules\jotr\node_modules\js-yaml\lib\js-yaml\loader.js:1331:12)
    at readBlockMapping (C:\Users\[username]\AppData\Roaming\npm\node_modules\jotr\node_modules\js-yaml\lib\js-yaml\loader.js:1062:11)
  name: 'YAMLException',
  reason: 'the stream contains non-printable characters',
  mark:
   Mark {
     name: null,
     buffer:
      "mongoose:\n  - |-\n    var query  = Kitten.where({ color: 'white' });\n    query.findOne(function (err, kitten) {\n      if (err) return handleError(err);\n      if (kitten) {\n        // doc may be null if no document matched\n      }\n    });\njavascript:\n  - |-\n    var query  = Kitten.where({ color: 'white' });\n    query.findOne(function (err, kitten) {\n      if (err) return handleError(err);\n      if (kitten) {\n        // doc may be null if no document matched\n      }\n    });\nquery:\n  - |-\n    var query  = Kitten.where({ color: 'white' });\n    query.findOne(function (err, kitten) {\n      if (err) return handleError(err);\n      if (kitten) {\n        // doc may be null if no document matched\n      }\n    });\nidee:\n  - Loop over userobjektet og se om feltene matcher.\nivantixml:\n  - respowerfuse.buildingblock.application.configuration.citrix.instantpassthru\b\b\b\b\b\b\b\b\b\n\u0000",
     position: 868,
     line: 30,
     column: 88 },
  message:
   'the stream contains non-printable characters at line 31, column 89:\n     ... .citrix.instantpassthru\b\b\b\b\b\b\b\b\b\n                                         ^' }
```

## attempted solutions
```powershell
PS C:\Users\[username]\Documents\certs> jotr --edit
[loadJots] There was a problem interpreting the file. It seems to be corrupted in some way. Run "jotr --list --debug" to display the error message.
PS C:\Users\[username]\Documents\certs> jotr --purge
[loadJots] There was a problem interpreting the file. It seems to be corrupted in some way. Run "jotr --list --debug" to display the error message.
```

## how to replicate issue
This issue started after i edited jots with `jotr --edit`

1. Edit file and remove **pasted** content, with "delete" and "backspace".
2. File should now be corrupt.

**Comment by hakash** [comment]
@dotkim The problem is identified as the corrupt characters that `tiny-cli-editor` inserts using `delete`. The issue will be resolved when `tiny-cli-editor` is replaced with `termit`, which is a priority.
